//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageName
{
    using System;
    using System.IO;
    using System.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    public enum EnumTestName
    {
        EnumTestName_None,
        EnumTestName_Test,
    }
    public partial class ClassName_t
    {
        public string member_str
        {
            get
            {
            }
            set
            {
            }
        }
        public int member_int32
        {
            get
            {
            }
            set
            {
            }
        }
    }
}
